# -*- coding: utf-8 -*-
"""İşaretler Ve Sistemler Ödev2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yVDPfScSDtoiEoHY4WIFFi_ukB1TYSvs
"""



import numpy as np
from scipy.io import wavfile
from google.colab import files
from IPython.display import Audio

# Frekans ve genlik değerlerinin listesi
frequencies = [250, 500, 1000, 2000, 4000,8000]
amplitudes = [0.05, 0.1, 2, 20, 40]

# İşaretin süresi (saniye cinsinden)
duration = 0.25

# İşaretlerin tutulacağı liste
signals = []

# Her frekans için işaretlerin oluşturulması
for freq in frequencies:
    # O anki frekans için genlik seviyeleriyle işaretlerin oluşturulması
    for amp in amplitudes:
        # İşaretin oluşturulması
        t = np.arange(0, duration, 1/44100)
        component = amp * np.sin(2*np.pi*freq*t)
        signal = np.int16(component*(2**15-1))
        signals.append((signal, freq, amp))  # işaret, frekans ve genlik seviyesi bir demet şeklinde listeye eklendi

# Tüm işaretlerin birleştirilmesi
total_signal = np.concatenate([signal for signal, freq, amp in signals])

# İşareti 16-bit PCM formatında kaydetme
wavfile.write('sinusoids.wav', 44150, total_signal)


# Kullanıcıya üretilen her bir işaretin frekans ve genlik değerlerini gösterme
for i, (signal, freq, amp) in enumerate(signals):
    print(f"Işaret {i+1}: Frekans: {freq} Hz, Genlik: {amp}")



# Ses dosyasını çalma
Audio('sinusoids.wav', autoplay=True)